import { ComponentProps } from 'react';
import { DesktopPosScreen, MobilePosScreen } from '../components';
import { MenuItem, PaidTicket, SessionSummary, TicketHistorySummary, TicketPeriodPreset } from '../types';
import type { PrinterDiagnostics, PrinterStatus } from '../services/api';

export type AppSection = 'home' | 'pos' | 'history' | 'products' | 'printer' | 'mobile-connect';
export type PosScreenProps = ComponentProps<typeof DesktopPosScreen> & ComponentProps<typeof MobilePosScreen>;

export interface MainScreenProps {
  activeSection: AppSection;
  setActiveSection: (section: AppSection) => void;
  goBack: () => void;
  goHome: () => void;
  onConfigureConnection: () => void;
  onLogout: () => void;
  onRefreshData: () => void;
  isRefreshingData: boolean;
  computerPairingUrl: string;
  posScreenProps: PosScreenProps;
  sessionSummary: SessionSummary | null;
  ticketHistorySummary: TicketHistorySummary;
  filteredPaidTickets: PaidTicket[];
  selectedPaidTicket: PaidTicket | null;
  ticketSearchText: string;
  setTicketSearchText: (value: string) => void;
  ticketPeriodPreset: TicketPeriodPreset;
  setTicketPeriodPreset: (value: TicketPeriodPreset) => void;
  ticketCustomStartDate: string;
  setTicketCustomStartDate: (value: string) => void;
  ticketCustomEndDate: string;
  setTicketCustomEndDate: (value: string) => void;
  ticketDateRangeLabel: string;
  ticketDateRangeError: string | null;
  selectPaidTicket: (ticket: PaidTicket) => void;
  clearSelectedPaidTicket: () => void;
  refreshSessionSummary: (showFeedback?: boolean) => Promise<void>;
  loadTicketHistory: () => Promise<void>;
  printSimplifiedPaidTicket: (ticket: PaidTicket) => Promise<void>;
  printFilteredTicketSummary: () => Promise<void>;
  downloadTicket: (ticket: PaidTicket) => Promise<void>;
  downloadFilteredTicketPdfs: () => Promise<void>;
  printerStatus: PrinterStatus | null;
  printerDiagnostics: PrinterDiagnostics | null;
  printerAction: 'refresh' | 'reconnect' | 'test' | 'cancel' | 'diagnostics' | null;
  refreshPrinterStatus: () => void;
  reconnectPrinter: () => void;
  runPrinterTest: () => void;
  cancelPendingPrinterJobs: () => void;
  openPrinterDiagnostics: () => void;
  managedCategories: string[];
  managedMenuItems: MenuItem[];
  productName: string;
  setProductName: (value: string) => void;
  productPrimaryName: string;
  setProductPrimaryName: (value: string) => void;
  productSecondaryName: string;
  setProductSecondaryName: (value: string) => void;
  productCategory: string;
  setProductCategory: (value: string) => void;
  productPrice: string;
  setProductPrice: (value: string) => void;
  productCost: string;
  setProductCost: (value: string) => void;
  productSku: string;
  setProductSku: (value: string) => void;
  productDescription: string;
  setProductDescription: (value: string) => void;
  productImageDataUrl: string | null;
  setProductImageDataUrl: (value: string | null) => void;
  importProductsCsv: () => void;
  chooseProductImage: (onSelected: (imageDataUrl: string) => void) => Promise<void>;
  saveNewProduct: () => Promise<void>;
  updateProductDetails: (item: MenuItem, values: { name: string; primaryName: string; secondaryName: string; category: string; price: string; cost: string }) => Promise<boolean>;
  updateProductName: (item: MenuItem, value: string) => Promise<void>;
  updateProductDisplayNames: (item: MenuItem, primaryName: string, secondaryName: string) => Promise<void>;
  updateProductCategory: (item: MenuItem, value: string) => Promise<void>;
  updateProductPrice: (item: MenuItem, value: string) => Promise<void>;
  updateProductCost: (item: MenuItem, value: string) => Promise<void>;
  updateProductImage: (item: MenuItem) => Promise<void>;
  removeProductImage: (item: MenuItem) => Promise<void>;
  removeProduct: (item: MenuItem) => void;
  formatDateTime: (value: string) => string;
  centsToCurrency: (cents: number) => string;
}
